# Generated by Django 4.2.29 on 2026-04-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livro_data_adicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
    ]
