# Generated by Django 4.2.29 on 2026-04-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_livro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('romance', 'Romance'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção Científica'), ('misterio', 'Mistério / Suspense'), ('terror', 'Terror'), ('biografia', 'Biografia'), ('historia', 'História'), ('autoajuda', 'Autoajuda'), ('poesia', 'Poesia'), ('aventura', 'Aventura'), ('infantil', 'Infantil'), ('didatico', 'Didático'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
    ]
