# Generated by Django 4.2.29 on 2026-04-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('ficcao_geral', 'Ficção Geral'), ('nao_ficcao_geral', 'Não Ficção Geral'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção Científica'), ('romance', 'Romance'), ('misterio_suspense', 'Mistério & Suspense'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('jovem_adulto', 'Jovem Adulto'), ('infantil', 'Infantil & Infanto-juvenil'), ('hq_manga', 'HQs, Mangás & Graphic Novels'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('academico', 'Acadêmicos'), ('historia_politica', 'História & Política'), ('religiao', 'Religião & Espiritualidade'), ('classica', 'Literatura Clássica'), ('contemporanea', 'Literatura Contemporânea'), ('drama', 'Drama'), ('poesia', 'Poesia'), ('teatro', 'Teatro (Peças)'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
    ]
