# Generated by Django 4.2.29 on 2026-06-26 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_perfil_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesejoFuturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desejado_futuramente_por', to='core.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desejos_futuros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='desejofuturo',
            constraint=models.UniqueConstraint(fields=('usuario', 'livro'), name='unique_desejo_futuro_usuario_livro'),
        ),
    ]
